---
- name: Configure Infrastructure
  hosts: all
  become: true
  tasks:
    - name: Create infra config file
      ansible.builtin.copy:
        content: "Infra Configured"
        dest: /etc/infra_config
        mode: '0644'
