---
- name: Configure Apache
  hosts: all
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
